// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class CreatelocationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createlocation() {
    driver.get("http://www.learnwebservices.com/locations/");
    driver.manage().window().setSize(new Dimension(1536, 824));
    driver.findElement(By.id("create-location-link")).click();
    driver.findElement(By.id("location-name")).click();
    driver.findElement(By.id("location-name")).sendKeys("Budapest");
    driver.findElement(By.cssSelector(".form-group:nth-child(2) em")).click();
    driver.findElement(By.id("location-coords")).click();
    driver.findElement(By.id("location-coords")).sendKeys("47.4979,19.0402");
    driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 3);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.id("message-div")));
    }
    assertThat(driver.findElement(By.id("message-div")).getText(), is("Location has created"));
  }
}
