// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.rules.ExpectedException;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
public class CreatelocationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    //driver = new ChromeDriver();
    driver=new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {

//    driver.quit();
  }
  @Test
  public void createlocation() throws InterruptedException, IOException {
    driver.get("http://www.learnwebservices.com/locations/");
    driver.manage().window().setSize(new Dimension(1536, 824));

    LocationsMainScreen screen = new LocationsMainScreen(driver);

    List<String> lines = Files.readAllLines(Path.of("MOCK_DATA.csv"));


    for (int i = 1; i < lines.size(); i++) {
      System.out.println(lines.get(i));
      String[] fields = lines.get(i).split(",");
      screen
              .kattintsALetrehozLinkre()
              //.toltsdKiAzUrlapot("Budapest", "20,10")
              .toltsdKiAzUrlapot(fields[0], fields[1] + "," + fields[2])
              .kuldElAKerdoivet()
              .ellenorizdHogyAzUzenet("Location has created");


    }
  }
}
